### ISSUE TITLE
Operator 'abs' not found

### ISSUE THREAD

**Issue by modulareverything** [yasinsolak/react-native-accordion-view#1]
I'm getting this error since starting to use this component. It only ever happens when the app first loads, and if I save it will load the app fine.

I found a potential fix here:
https://stackoverflow.com/questions/63315761/react-native-getting-this-error-unrecognized-operator-abs

But running this command doesn't actually fix the issue:
`expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view` 

Any ideas?

**Comment by yasinsolak** [comment]
Can you try that
```yarn add react-native-redash```

**Comment by modulareverything** [comment]
Thanks for the quick reply @yasinsolak — unfortunately that didn't work and I'm still getting the same error above

**Comment by yasinsolak** [comment]
You're welcome, I'm trying to do my best.

I encountered the same error in a new project. This solved my problem:

https://stackoverflow.com/questions/63215154/react-native-reanimated-unable-to-resolve-usevalue

**Comment by modulareverything** [comment]
@yasinsolak I forgot to say that this didn't actually work! But I'm not sure what other information to provide which might help debug it
